using System;
using System.Collections.Generic;
using System.Linq;

namespace EulerProject.Business
{
    public class Problem2 : Problem
    {
        /// <summary>
        /// Each new term in the Fibonacci sequence is generated by adding
        /// the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        /// By considering the terms in the Fibonacci sequence whose values
        /// do not exceed four million, find the sum of the even-valued terms.
        /// </summary>

        public override void Init()
        {
            throw new NotImplementedException();
        }

        public override void Execute()
        {
            int max = 4000000;
            Console.WriteLine(string.Format("Result: {0}", GetResult(max)));
        }

        private static int GetResult(int max)
        {
            List<int> values = new List<int>();
            int current = 1, next = 2, val = 2;
            while (val < max)
            {
                if (val % 2 == 0)
                    values.Add(val);
                val = current + next;
                current = next;
                next = val;
            }
            return values.Sum();
        }
    }
}